ALTER TABLE users
  ADD COLUMN IF NOT EXISTS bio         TEXT,
  ADD COLUMN IF NOT EXISTS institution VARCHAR(200),
  ADD COLUMN IF NOT EXISTS department  VARCHAR(150),
  ADD COLUMN IF NOT EXISTS phone       VARCHAR(30),
  ADD COLUMN IF NOT EXISTS degree      VARCHAR(100);
